name: Build and test

on:
  push:
    branches:
      - master
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build devcontainer image
      uses: devcontainers/ci@v0.3
      with:
        runCmd: devenv test